# Server
server.port=8080

# PostgreSQL DB
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=ecom_user
spring.datasource.password=ecom_pass

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true



# Recommended: avoid open-in-view issues later
spring.jpa.open-in-view=false
jwt.secret=mysupersecretmysupersecretmysupersecretmysupersecret
jwt.expiration=86400000
